name: Cypress Tests

on:
    push:
    workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false  
      matrix:
        browsers: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run in ${{ matrix.browsers }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser s}}
          command: npx cypress run --browser  ${{ matrix.browsers }} --reporter-options reportDir=cypress/reports${{ matrix.browsers }}
      - name: Merge Mochawesome Reports
      run: npx mochawesome-merge cypress/reports/${{ matrix.browsers }}*.json > cypress/reports/${{ matrix.browsers }}/merged-reports.json

      -name: Generate HTML Reports 
        run: npx merge cypress/reports/${{ matrix.browsers }}/merged-reports.json --reportDir cypress/reports/${{ matrix.browsers }} -f "${{ matrix.browsers }}-report.html"
      
      -name: Upload HTML Report
       uses: actions/upload-artifact@v4 
       with: 
           name: Cypress HTML Report ${{ matrix.browsers }}
           path: cypress/reports/${{ matrix.browsers }}

        