name: Cypress Tests

on: workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox, edge]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          npm install mochawesome --save-dev

      - name: Cypress run in ${{ matrix.browsers }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browsers }}
          command: npx cypress run --browser ${{ matrix.browsers }}

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: Cypress HTML Reports ${{ matrix.browsers }}
          path: cypress/reports/*.html
